name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:  

jobs:
  build-and-test:
    name: Build & Test Backend (Maven + Jacoco)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: campaign
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Cache Maven repo
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('campaign/pom.xml') }}
      - name: Build & run tests
        run: mvn clean verify --batch-mode

  lint-frontend:
    name: Frontend lint (ESLint + Prettier)
    runs-on: ubuntu-latest
    needs: build-and-test
    defaults:
      run:
        working-directory: campaign-frontend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install deps & lint
        run: |
          npm ci
          npx eslint src --max-warnings=0
          npx prettier --check .

  deploy-to-heroku:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: [ build-and-test, lint-frontend ]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Heroku Container Login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:login

      - name: Build & Push Docker image
        run: |
          docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web campaign
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      - name: Release on Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
