name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build & Test Backend (Maven + Jacoco)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: campaign
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Cache Maven repo
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('campaign/pom.xml') }}
      - name: Build & run tests
        run: mvn clean verify --batch-mode

  lint-frontend:
    name: Frontend lint (ESLint + Prettier)
    runs-on: ubuntu-latest
    needs: build-and-test
    defaults:
      run:
        working-directory: campaign-frontend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install deps & lint
        run: |
          npm ci
          npx eslint src --max-warnings=0
          npx prettier --check .

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: [build-and-test, lint-frontend]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

     
      - name: Heroku Container Login
        run: heroku container:login

      - name: Deploy Docker container to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
